version: '3.8'

services:
  mongo-dev:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data-dev:/data/db
    restart: always

  redis-dev:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    restart: always

  minio-dev:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data-dev:/data
    command: server /data --console-address ":9001"
    restart: always

  createbuckets-dev:
    image: minio/mc
    depends_on:
      - minio-dev
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio-dev:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ssex-images;
      /usr/bin/mc anonymous set public myminio/ssex-images;
      exit 0;
      "

volumes:
  mongo-data-dev:
  redis-data-dev:
  minio-data-dev:
